site_name: Katana Documentation
site_author: Polygon Labs
copyright: Copyright &copy; PT Services DMCC 2025
repo_name: Katana Documentation
repo_url: https://github.com/agglayer/agglayer-docs
edit_uri: edit/main/docs/
site_url: https://agglayer.dev/

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: "#FF8E08"
  language: en
  custom_dir: overrides
  favicon: img/katana/favicon.ico
  logo: img/katana/k-logo.svg
  icon:
    logo: logo
    repo: repo
  features:
    - search.suggest
    - search.highlight
    - search.share
    #- navigation.instant #
    #- navigation.instant.progress
    - navigation.tracking
    - navigation.integration
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

nav:
  - Agglayer:
      - Overview: index.md
      - Get Started:
          - Set up your environment: agglayer/get-started/bridge-assets.md
      - How To:
          - Bridge an ERC-20 token: agglayer/how-to/transfer-asset.md
          - Call a smart contract cross-chain: agglayer/how-to/call-contract.md
          - Bridge-and-call in one step: agglayer/how-to/transfer-and-call.md
      - Core Concepts:
          - Architecture: agglayer/core-concepts/architecture.md
          - Unified Bridge: agglayer/core-concepts/unified-bridge.md
          - Pessimistic Proof: agglayer/core-concepts/pessimistic-proof.md
          # - Multi-stack Interop: agglayer/core-concepts/connecting-chains.md
      - Additional Resources:
          - Connected Chains: agglayer/add-res/connected-chains.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-PM6L5JWEZP
  social:
    - icon: fontawesome/solid/circle-question
      link: https://support.polygon.technology/support/solutions
    - icon: fontawesome/solid/globe
      link: https://agglayer.dev/
    - icon: fontawesome/brands/github
      link: https://github.com/agglayer/agglayer-docs
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - _site_essentials/stylesheets/extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  #- md_in_html
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - search
  - open-in-new-tab
  - redirects:
      redirect_maps:
        "docs/develop/network-details/network.md": "cdk/index.md"
        "cdk/getting-started/index.md": "cdk/getting-started/local-deployment.md"
        "zkEVM/how-to/index.md": "zkEVM/get-started/index.md"
        "cdk/concepts/index.md": "cdk/concepts/layer2s.md"
        "tools/matic-js/installation.md": "tools/matic-js/get-started.md"
        "pos/how-to/access-node.md": "tools/dApp-development/tutorials/access-node.md"
        "pos/how-to/full-node/full-node-system-requirements.md": "pos/how-to/prerequisites.md"
        "pos/how-to/validator/prerequisites.md": "pos/how-to/prerequisites.md"
        "pos/how-to/validator/validator-system-requirements.md": "pos/how-to/prerequisites.md"
        "pos/how-to/choose-node-type.md": "pos/how-to/prerequisites.md"
        "pos/how-to/operate-validator-node/validator-best-practices.md": "pos/how-to/validator/validator-best-practices.md"
        "pos/how-to/operate-validator-node/validator-commission-operations.md": "pos/how-to/operate-validator-node/next-steps.md"
        "pos/how-to/operate-validator-node/validator-staking-operations.md": "pos/how-to/operate-validator-node/next-steps.md"
        "pos/how-to/operating/validator-node/index.md": "pos/how-to/operate-validator-node/next-steps.md"
        "cdk/version-matrix/index.md": "index.md"

validation:
  absolute_links: warn
  anchors: warn

extra_javascript:
  - _site_essentials/js/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?version=4.8.0
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
