site_name: Katana Documentation
site_author: Katana Services (Cayman)
copyright: Copyright &copy; Katana Services (Cayman)
repo_name: Katana Documentation
repo_url: https://github.com/katana-network/katana-docs
edit_uri: edit/main/docs/
site_url: docs.katana.network

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: "#FF8E08"
  language: en
  custom_dir: overrides
  favicon: img/katana/favicon.ico
  logo: img/katana/k-logo.svg
  icon:
    logo: logo
    repo: repo
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.integration
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.action.edit

nav:
  - Katana:
      - Overview: index.md
      - Get Started:
          - Set up your environment: katana/get-started/set-up-your-environment.md
          - Technical reference [testnet]: katana/get-started/technical-reference-testnet.md
          - Request testnet credentials: "https://forms.clickup.com/90131276658/f/2ky3w8vj-4573/KHGUSZC4VHAMX9XMYN"
          - Use MCP to talk to the blockchain: katana/get-started/use-mcp.md
      - How To:
          - Read token balances and wrap ETH into WETH: katana/how-to/read-balances-and-wrap-eth.md
          - Verify contracts on Tatara: katana/how-to/verify-contracts-on-tatara.md
          - Build a token launchpad app: katana/how-to/build-a-token-launchpad.md
          - Integrate Privy email login (client side): katana/how-to/add-privy.md
      - Core Concepts:
          - Vault Bridge: katana/core-concepts/vault-bridge.md
          - Chain-Owned Liquidity: katana/core-concepts/chain-owned-liquidity.md
          - CDK-opgeth: katana/core-concepts/cdk-opgeth.md
          - Risk: katana/core-concepts/risk.md
          - Governance: katana/core-concepts/governance.md
          - Sustainability: katana/core-concepts/sustainability.md
      - Additional Resources:
          - Katana Developer Community: katana/additional-resources/community-page.md
          # - Technical reference [mainnet]: katana/additional-resources/technical-reference-mainnet.md
          - Katana Protocol Terms & Conditions: katana/additional-resources/katana-terms-and-conditions.md

extra:
  generator: false
  analytics:
    provider: google
    property: G-CQM8J9D2Q8
  social:
    - icon: fontawesome/solid/globe
      link: https://katana.network/
    - icon: fontawesome/brands/github
      link: https://github.com/katana-network/katana-docs/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/katananetwork
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/katana/
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_css:
  - _site_essentials/stylesheets/extra.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret
  - meta
  - smarty
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - search
  - open-in-new-tab
  - redirects:
      redirect_maps:
        "docs/develop/network-details/network.md": "cdk/index.md"
        "cdk/getting-started/index.md": "cdk/getting-started/local-deployment.md"
        "zkEVM/how-to/index.md": "zkEVM/get-started/index.md"
        "cdk/concepts/index.md": "cdk/concepts/layer2s.md"
        "tools/matic-js/installation.md": "tools/matic-js/get-started.md"
        "pos/how-to/access-node.md": "tools/dApp-development/tutorials/access-node.md"
        "pos/how-to/full-node/full-node-system-requirements.md": "pos/how-to/prerequisites.md"
        "pos/how-to/validator/prerequisites.md": "pos/how-to/prerequisites.md"
        "pos/how-to/validator/validator-system-requirements.md": "pos/how-to/prerequisites.md"
        "pos/how-to/choose-node-type.md": "pos/how-to/prerequisites.md"
        "pos/how-to/operate-validator-node/validator-best-practices.md": "pos/how-to/validator/validator-best-practices.md"
        "pos/how-to/operate-validator-node/validator-commission-operations.md": "pos/how-to/operate-validator-node/next-steps.md"
        "pos/how-to/operate-validator-node/validator-staking-operations.md": "pos/how-to/operate-validator-node/next-steps.md"
        "pos/how-to/operating/validator-node/index.md": "pos/how-to/operate-validator-node/next-steps.md"
        "cdk/version-matrix/index.md": "index.md"

validation:
  absolute_links: warn
  anchors: warn

extra_javascript:
  - _site_essentials/js/mathjax.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?version=4.8.0
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
