[tool.semantic_release]
version_variable = "mkdocs_version.py:__version__"
branch = "main"
upload_to_pypi = false
build_command = "echo 'No build step needed for MkDocs'"
commit_parser = "angular"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG.md"