[tool.semantic_release]
version_variable = "mkdocs_version.py:__version__"
branch = "main"
upload_to_pypi = false
build_command = "echo 'No build step needed for MkDocs'"

[tool.semantic_release.changelog]
changelog_file = "CHANGELOG.md"

[tool.semantic_release.commit_parser]
parser = "angular"