name: Agglayer docs AWS Deployment
on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      environment:
        required: false
        type: choice
        description: "Select the environment to deploy to (optional for pushes)"
        options:
          - prod

permissions:
  contents: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/build_and_deploy.yml
    with:
      environment: ${{ inputs.environment || 'dev' }}
      core_app: agglayer-docs
    secrets: inherit