name: Release
on:
  push:
    branches:
      - main
jobs:
  semantic-versioning:
    name: Semantic Versioning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.SEMANTIC_RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.SEMANTIC_RELEASE_BOT_APP_KEY }}

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
  
      - name: Install pipenv
        run: pip install pipenv
  
      - name: Install dependencies
        run: pipenv install --dev
  
      - name: Run python-semantic-release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pipenv run semantic-release publish